import { describe, expect, it } from 'vitest';
import { partialHash } from './partial-hash';

const WINDOW = 64 * 1024;

/** Deterministic filler, so a fixture pins the byte layout and not a coincidence. */
const fill = (n: number) =>
  new Blob([Uint8Array.from({ length: n }, (_, i) => (i * 31 + 7) % 251)]);

/**
 * Generated by running Winnow's own `partialHash()` (`src/lib/hash.ts` in
 * `CostardRouge/winnow`) over the same buffers. These are the contract: if one
 * ever fails, this implementation has drifted from the one that fills
 * `assets.content_hash`, and every id→hash→name resolution silently degrades to
 * name-only. Regenerate from Winnow, never from here.
 */
const FIXTURES: [size: number, hash: string][] = [
  [0, '5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9'],
  [1, '96c625c697713722aa513217b755ac4cdbc53836859d8beca0d408bc1f232b5b'],
  [10, 'b52924d78a2fd83a685e0039d1c90601fc05802867e3ad13986973e563d8d5f5'],
  [WINDOW - 1, '912a7f2a704108fdbca0540a3d385dde90660f92d1d36eb4637bb61c7afd3b64'],
  [WINDOW, '4e7d02ea7951fdd94e325e26b3b46b414e1b11daf32084be9674201552f8f4cc'],
  [WINDOW + 1, 'd84a23839ef20ed7fdc2d228ae7162f9cf697d3bfaff5bd0d00d272a9ebb6baf'],
  [3 * WINDOW, '0074435d84736d170f356078e8d1bc2dcc138f30b3b49da407f594f368f873e9'],
];

describe('partialHash', () => {
  it.each(FIXTURES)('matches Winnow byte-for-byte at size %i', async (size, expected) => {
    expect(await partialHash(fill(size))).toBe(expected);
  });

  it('hashes an empty file as the size prefix alone', async () => {
    // sha256("0") — proof the decimal size is hashed as text, not as bytes.
    expect(await partialHash(new Blob([]))).toBe(
      '5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9',
    );
  });

  it('separates two files of the same size that differ in their first bytes', async () => {
    const a = fill(3 * WINDOW);
    const b = new Blob([new Uint8Array([255]), (await a.arrayBuffer()).slice(1)]);
    expect(await partialHash(a)).not.toBe(await partialHash(b));
  });

  it('separates two files that differ only in their last bytes', async () => {
    const bytes = new Uint8Array(await fill(3 * WINDOW).arrayBuffer());
    const tweaked = bytes.slice();
    tweaked[tweaked.length - 1] ^= 0xff;
    expect(await partialHash(new Blob([bytes]))).not.toBe(
      await partialHash(new Blob([tweaked])),
    );
  });

  it('separates two identical files of different lengths', async () => {
    expect(await partialHash(fill(100))).not.toBe(await partialHash(fill(101)));
  });

  it('COLLIDES when only the middle differs — the documented limit', async () => {
    // Neither window covers byte WINDOW+100, so the two hashes are equal by
    // construction. This is why a hash match is evidence, not proof, and why
    // reconciliation keeps the name as a tiebreak.
    const bytes = new Uint8Array(await fill(3 * WINDOW).arrayBuffer());
    const middleChanged = bytes.slice();
    middleChanged[WINDOW + 100] ^= 0xff;
    expect(await partialHash(new Blob([bytes]))).toBe(
      await partialHash(new Blob([middleChanged])),
    );
  });
});
