// Port of `src/shared/lib/partial-hash.test.ts`.

import Foundation
import XCTest
@testable import AtelierKit

private let window = 64 * 1024

/// Deterministic filler, so a fixture pins the byte layout and not a coincidence.
private func fill(_ n: Int) -> Data {
    Data((0..<n).map { UInt8(($0 * 31 + 7) % 251) })
}

/// Generated by running Winnow's own `partialHash()` (`src/lib/hash.ts` in
/// `CostardRouge/winnow`) over the same buffers. These are the contract: if
/// one ever fails, this implementation has drifted from the one that fills
/// `assets.content_hash`, and every id→hash→name resolution silently degrades
/// to name-only. Regenerate from Winnow, never from here.
private let fixtures: [(size: Int, hash: String)] = [
    (0, "5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9"),
    (1, "96c625c697713722aa513217b755ac4cdbc53836859d8beca0d408bc1f232b5b"),
    (10, "b52924d78a2fd83a685e0039d1c90601fc05802867e3ad13986973e563d8d5f5"),
    (window - 1, "912a7f2a704108fdbca0540a3d385dde90660f92d1d36eb4637bb61c7afd3b64"),
    (window, "4e7d02ea7951fdd94e325e26b3b46b414e1b11daf32084be9674201552f8f4cc"),
    (window + 1, "d84a23839ef20ed7fdc2d228ae7162f9cf697d3bfaff5bd0d00d272a9ebb6baf"),
    (3 * window, "0074435d84736d170f356078e8d1bc2dcc138f30b3b49da407f594f368f873e9"),
]

/// A blob that hands out slices lazily and remembers what was asked of it —
/// what the app wraps a file handle in, so the spec pins how much is read.
private final class RecordingBlob: HashableBlob {
    let bytes: Data
    var asked: [(Int, Int)] = []
    init(_ bytes: Data) { self.bytes = bytes }
    var size: Int { bytes.count }
    func slice(_ start: Int, _ end: Int) throws -> Data {
        asked.append((start, end))
        return bytes.subdata(in: start..<end)
    }
}

final class PartialHashTests: XCTestCase {
    func testMatchesWinnowByteForByteAtEverySize() throws {
        for f in fixtures {
            XCTAssertEqual(partialHash(fill(f.size)), f.hash, "size \(f.size)")
            XCTAssertEqual(try partialHash(RecordingBlob(fill(f.size))), f.hash, "blob of size \(f.size)")
        }
    }

    func testHashesAnEmptyFileAsTheSizePrefixAlone() {
        // sha256("0") — proof the decimal size is hashed as text, not as bytes.
        XCTAssertEqual(partialHash(Data()), "5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9")
    }

    func testSeparatesTwoFilesOfTheSameSizeThatDifferInTheirFirstBytes() {
        let a = fill(3 * window)
        var b = a
        b[b.startIndex] = 255
        XCTAssertNotEqual(partialHash(a), partialHash(b))
    }

    func testSeparatesTwoFilesThatDifferOnlyInTheirLastBytes() {
        let bytes = fill(3 * window)
        var tweaked = bytes
        tweaked[tweaked.count - 1] ^= 0xff
        XCTAssertNotEqual(partialHash(bytes), partialHash(tweaked))
    }

    func testSeparatesTwoIdenticalFilesOfDifferentLengths() {
        XCTAssertNotEqual(partialHash(fill(100)), partialHash(fill(101)))
    }

    func testCollidesWhenOnlyTheMiddleDiffersTheDocumentedLimit() {
        // Neither window covers byte WINDOW+100, so the two hashes are equal by
        // construction. This is why a hash match is evidence, not proof, and
        // why reconciliation keeps the name as a tiebreak.
        let bytes = fill(3 * window)
        var middleChanged = bytes
        middleChanged[window + 100] ^= 0xff
        XCTAssertEqual(partialHash(bytes), partialHash(middleChanged))
    }

    func testReadsAtMostTheTwoWindowsWhateverTheFileWeighs() throws {
        // The property the protocol exists for: a file is never loaded whole.
        let big = RecordingBlob(fill(3 * window))
        _ = try partialHash(big)
        XCTAssertEqual(big.asked.map { $0.0 }, [0, 2 * window])
        XCTAssertEqual(big.asked.map { $0.1 }, [window, 3 * window])

        let small = RecordingBlob(fill(10))
        _ = try partialHash(small)
        XCTAssertEqual(small.asked.count, 1)

        // Just over the threshold the tail is the ONE byte the head left.
        let over = RecordingBlob(fill(window + 1))
        _ = try partialHash(over)
        XCTAssertEqual(over.asked.map { $0.0 }, [0, window])
        XCTAssertEqual(over.asked.map { $0.1 }, [window, window + 1])
    }

    func testADataSliceKeepsItsParentIndices() {
        // A `Data` cut out of a larger one starts past index 0; the hash must
        // read ITS bytes, not the parent's.
        let parent = fill(3 * window + 50)
        let inner = parent.subdata(in: 50..<(3 * window + 50))
        let sliced = parent[50...]
        XCTAssertEqual(partialHash(sliced), partialHash(inner))
    }
}
