// A film stock as a LAYER of the look stack — `source: "film"`, its settings
// in the layer's `customText` as JSON, its cube GENERATED from them. Port of
// `src/shared/film/film-layer.ts`.
//
// Why a layer and not a stage beside the develop: a conversion LUT must run
// BEFORE the film response (an emulsion applied to D-Log is nonsense) and
// only the layer list is ordered by the author. As a layer, everything a look
// already has — strength, bypass, order, the three Trips rungs, the house
// style, both file formats — works with no document migration
// (`docs/film-simulation.md` F2).
//
// The generated cube is CACHED by its settings, and that cache is not an
// optimisation but the feature's viability: generating a 33³ cube runs the
// emulsion 36 000 times (~106 ms measured on the web) while composing the
// layer at some strength costs ~4 ms, so the strength slider must never re-run
// the emulsion (`media-pipeline.md`). The cache is module state behind a lock,
// as the web's is module state; `CubeLut` is a value, so "the same cube" is
// the same VALUE here, never an identity.

import Foundation

/// The `source` a film layer carries.
public let filmSource = "film"

public func isFilmLayer(_ layer: LutLayer) -> Bool {
    layer.source == filmSource
}

public func isFilmLayer(_ layer: SavedLutLayer) -> Bool {
    layer.source == filmSource
}

/// Generated cubes kept, by settings. A 33³ cube is ~430 KB; a dial drag walks a few dozen.
private let maxCachedCubes = 24

private final class FilmCubeCache: @unchecked Sendable {
    private let lock = NSLock()
    private var cubes: [String: CubeLut] = [:]

    /// The cube under `key`, generated by `make` once per distinct key. The
    /// lock is held across the generation so two threads asking for one
    /// settings pay it once.
    func cube(for key: String, make: () -> CubeLut) -> CubeLut {
        lock.lock()
        defer { lock.unlock() }
        if let known = cubes[key] { return known }
        if cubes.count >= maxCachedCubes { cubes.removeAll() }
        let cube = make()
        cubes[key] = cube
        return cube
    }

    func clear() {
        lock.lock()
        defer { lock.unlock() }
        cubes.removeAll()
    }
}

private let cubeCache = FilmCubeCache()

/// The cube for these settings — generated once per distinct settings, then read.
public func filmCubeFor(_ settings: FilmSettings) -> CubeLut {
    cubeCache.cube(for: filmSettingsKey(settings)) {
        filmCube(settings, title: describeFilm(settings))
    }
}

/// Tests only.
public func clearFilmCubeCache() {
    cubeCache.clear()
}

/// A stored film layer, parsed and ready to bake — or nil when its text is
/// not film settings, in which case the layer must be visibly missing, never
/// silently neutral (`restore-grade.ts`'s rule for every look).
public func filmLayerFromSaved(_ saved: SavedLutLayer) -> LutLayer? {
    guard isFilmLayer(saved), let settings = readFilmSettings(saved.customText) else { return nil }
    return LutLayer(
        id: saved.id,
        source: filmSource,
        name: describeFilm(settings),
        lut: filmCubeFor(settings),
        intensity: saved.intensity,
        enabled: saved.enabled
    )
}

/// A fresh layer seeded from a stock, plus the text the stack stores for it.
public func newFilmLayer(_ id: String, _ stockId: FilmStockId) -> (layer: LutLayer, text: String) {
    let settings = filmSettingsFor(stockId)
    let layer = LutLayer(
        id: id,
        source: filmSource,
        name: describeFilm(settings),
        lut: filmCubeFor(settings),
        intensity: 1,
        enabled: true
    )
    return (layer, writeFilmSettings(settings))
}

/// The same layer over new settings: its name says where it now stands, its cube is regenerated.
public func withFilmSettings(_ layer: LutLayer, _ settings: FilmSettings) -> (layer: LutLayer, text: String) {
    var next = layer
    next.name = describeFilm(settings)
    next.lut = filmCubeFor(settings)
    return (next, writeFilmSettings(settings))
}
